version: '3.8'

services:
  # Create the GUI that shows the turtle swimming around.
  turtlesim:
    image: turtlesim_teleop:sim
    container_name: turtlesim
    networks: 
      - ros
    build:
      context: .
      dockerfile: ./turtlesim.Dockerfile
      args: 
        ROS_DISTRO: foxy
  # Create a container for RQT.
  rqt:
    image: turtlesim_teleop:rqt
    container_name: rqt
    networks: 
      - ros
    build: 
      context: .
      dockerfile: ./rqt.Dockerfile
      args: 
        ROS_DISTRO: foxy

# Set up a network that other containers can use to communicate with these nodes.
networks: 
  ros:
    name: ros
    attachable: true